package fr.poutchinystudio.whirling_back.enums;

public enum Phases {
    SETUP, PLAY_RECIPES, REVEAL_RECIPES, RESOLVE_ARCANA, PRODUCE_INGREDIENTS, PASS_CAULDRONS, CHECK_FOR_WINNERS, PASS_RECIPE_CARDS
}
